apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-auth-ingress
  annotations:
    konghq.com/plugins: "basic-auth-plugin"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /basic-auth
        pathType: Exact 
        backend: 
          service: 
            name: echo
            port:
              number: 80