packages:
  - npm
  - nodejs
  - git
write_files:
- encoding: b64
  content: Y2QgL2hvbWUvdWJ1bnR1CmN1cmwgLUwgaHR0cHM6Ly9kb2NzLmtvbmdocS5jb20vbWVzaC9pbnN0YWxsZXIuc2ggfCBzaCAtCnN1ZG8gY3Aga29uZy1tZXNoLSovYmluLyogL3Vzci9sb2NhbC9iaW4vCgojIGluc3RhbGwgbnBtCiMgY2xvbmUgYW5kIHJ1biBkZW1vIGFwcApucG0gaW5zdGFsbCBleHByZXNzCm5wbSBpbnN0YWxsIGlvcmVkaXMKZ2l0IGNsb25lIGh0dHBzOi8vZ2l0aHViLmNvbS9rdW1haHEva3VtYS1jb3VudGVyLWRlbW8uZ2l0CgoKY2F0IDw8RU9GID4gL2hvbWUvdWJ1bnR1L2RhdGFwbGFuZS1hcHAueWFtbAogIHR5cGU6IERhdGFwbGFuZQogIG1lc2g6IGRlZmF1bHQKICBuYW1lOiBkZW1vLWFwcAogIG5ldHdvcmtpbmc6IAogICAgYWRkcmVzczogJChob3N0bmFtZSAtSSkKICAgIG91dGJvdW5kOgogICAgICAtIHBvcnQ6IDE2Mzc5CiAgICAgICAgdGFnczoKICAgICAgICAgIGt1bWEuaW8vc2VydmljZTogcmVkaXMKICAgIGluYm91bmQ6IAogICAgICAtIHBvcnQ6IDE1MDAwCiAgICAgICAgc2VydmljZVBvcnQ6IDUwMDAKICAgICAgICBzZXJ2aWNlQWRkcmVzczogMTI3LjAuMC4xCiAgICAgICAgdGFnczogCiAgICAgICAgICBrdW1hLmlvL3NlcnZpY2U6IGFwcAogICAgICAgICAga3VtYS5pby9wcm90b2NvbDogaHR0cApFT0YKCgprdW1hY3RsIGNvbmZpZyBjb250cm9sLXBsYW5lcyBhZGQgLS1hZGRyZXNzIGh0dHA6Ly9tZXNoLWNwOjU2ODEgLS1uYW1lIG1lc2gtY3AgLS1vdmVyd3JpdGUKa3VtYWN0bCBnZW5lcmF0ZSBkYXRhcGxhbmUtdG9rZW4gLS1uYW1lPWRlbW8tYXBwID4gL2hvbWUvdWJ1bnR1L2t1bWEtdG9rZW4tZGVtbyAKCnN5c3RlbWN0bCBkYWVtb24tcmVsb2FkCnN5c3RlbWN0bCBzdGFydCBkZW1vLnNlcnZpY2UKc3lzdGVtY3RsIGVuYWJsZSBkZW1vLnNlcnZpY2UKCnN5c3RlbWN0bCBzdGFydCBrdW1hLmRwLnNlcnZpY2UKc3lzdGVtY3RsIGVuYWJsZSBrdW1hLmRwLnNlcnZpY2UKCg==
  owner: root:root
  path: /kuma/enable-dp.sh
  permissions: '0755'
- path: /etc/systemd/resolved.conf
  append: true
  content: |
    MulticastDNS=yes
- path: /etc/systemd/system/mdns@.service
  content: |
    [Service]
    Type=oneshot
    ExecStart=/usr/bin/systemd-resolve --set-mdns=yes --interface=%i
    After=sys-subsystem-net-devices-%i.device

    [Install]
    WantedBy=sys-subsystem-net-devices-%i.device
- path: /etc/systemd/system/demo.service
  content: |
    [Unit]
    Description=Kuma demo app
    
    [Service]
    Environment="REDIS_HOST=redis-dp"
    Environment="REDIS_PORT=26379"
    User=root
    WorkingDirectory=/home/ubuntu/kuma-counter-demo
    ExecStart=npm start --prefix=/home/ubuntu/kuma-counter-demo/app
    Restart=always
    
    [Install]
    WantedBy=multi-user.target
- path: /etc/systemd/system/kuma.dp.service
  content: |
    [Unit]
    Description=Kuma demo dp
    
    [Service]
    User=root
    WorkingDirectory=/usr/local/bin
    ExecStart=kuma-dp run --cp-address=https://mesh-cp:5678/ --dns-enabled=false --dataplane-token-file=/home/ubuntu/kuma-token-demo --dataplane-file=/home/ubuntu/dataplane-app.yaml
    Restart=always
    
    [Install]
    WantedBy=multi-user.target
runcmd:
    - [ /usr/bin/sh, -c, /kuma/enable-dp.sh ]
    - [ /usr/bin/chown, -R, ubuntu:ubuntu, /home/ubuntu ]
    - systemctl restart systemd-resolved.service
    - systemctl start mdns@enp0s2.service
    - systemctl enable mdns@enp0s2.service