image:
  repository: kong/kong-gateway
  # tag: 2.5.1.2
  tag: 2.8.2.1
  pullSecrets:
    - kong-enterprise-edition-docker

env:
  admin_gui_url: https://kongfused.local:8445
  admin_listen: 0.0.0.0:8001, 0.0.0.0:8444 ssl
  log_level: debug
  admin_gui_auth_conf_secret: kong-session-config
  admin_api_uri: https://kongfused.local:8444
  database: postgres
  # admin_gui_ssl_cert_key:  /etc/secrets/kong-mngr-tls/tls.key
  # ssl_cert: /etc/secrets/kong-proxy-tls/tls.crt
  # ssl_cert_key:  /etc/secrets/kong-proxy-tls/tls.key
  # admin_ssl_cert: /etc/secrets/kong-admin-tls/tls.crt
  # admin_ssl_cert_key:  /etc/secrets/kong-admin-tls/tls.key
  # admin_gui_ssl_cert:  /etc/secrets/kong-mngr-tls/tls.crt
  
  password:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password 
        key: password 
  kong_admin_token:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password
        key: password
  admin_gui_session_conf:
      valueFrom:
      secretKeyRef:
        name: kong-session-config
        key: admin_gui_session_conf

admin:
  enabled: true
  type: LoadBalancer
  annotations:
    konghq.com/protocol: "https"

  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001

  tls:
    enabled: true
    servicePort: 8444
    containerPort: 8444
    parameters:
    - http2

proxy:
  enabled: true
  type: LoadBalancer
  annotations: {}

  http:
    enabled: true
    servicePort: 8000
    containerPort: 8000
    parameters: []

  tls:
    enabled: true
    servicePort: 8443
    containerPort: 8443
    parameters:
    - http2

  stream: {}



enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  vitals:
    enabled: true
  portal:
    enabled: true
  rbac:
    enabled: true
    admin_gui_auth: basic-auth
    admin_gui_auth_conf_secret: kong-session-config

manager:
  enabled: true
  type: LoadBalancer

  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002

  tls:
    enabled: true
    servicePort: 8445
    containerPort: 8445
    parameters:
    - http2

portal:
  enabled: true
  type: LoadBalancer

  http:
    enabled: true
    servicePort: 8003
    containerPort: 8003
    parameters: []

  tls:
    enabled: true
    servicePort: 8446
    containerPort: 8446
    parameters:
    - http2

portalapi:
  enabled: true
  type: LoadBalancer
  annotations:
    konghq.com/protocol: "https"

  http:
    enabled: true
    servicePort: 8004
    containerPort: 8004
    parameters: []

  tls:
    enabled: true
    servicePort: 8447
    containerPort: 8447
    parameters:
    - http2


postgresql:
  enabled: false
  auth:
    username: kong
    database: kong
  image:
    tag: 13.6.0-debian-10-r52
  service:
    ports:
      postgresql: "5432"

ingressController:
  enabled: true
  image:
    repository: kong/kubernetes-ingress-controller
    tag: "2.7"
  installCRDs: false
  env:
    kong_admin_token:
      valueFrom:
        secretKeyRef:
          name: kong-enterprise-superuser-password
          key: password 